export const PageEnums = {
    MY_DASHBOARD: 'my dashboard',
    WIDGET_STYLES: 'WIDGET_STYLES',
    NOTIFICATIONS: 'NOTIFICATIONS',
    NEW_DASHBOARD: 'new dashboard',
    APPLICATION: 'application',
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',
    PREVIEW_DASHBOARD: 'PREVIEW_DASHBOARD',
    DATA_METRICS: 'DATA_METRICS',
    THRESHOLDS: 'THRESHOLDS',
    LOGIN: 'LOGIN'
  }